name: cp-insights
description: Competitive Programming Insights
url: "https://cp-insights.github.io"
markdown: kramdown
highlighter: rouge
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-latex